events {}

http {
    upstream test_backend_cluster {
        server test-queueing-back-1:8080;
        server test-queueing-back-2:8080;
        server test-queueing-back-3:8080;
    }

    server {
        listen 90;

        # 79포트로 요청이 오면 Nginx는 그 요청을 backend_cluster라는 이름의 서버 그룹으로 전달(proxy)
        location / {
            proxy_pass http://test_backend_cluster;
        }
    }
}

