spring.application.name=QueueTest
server.port=8080

move.to.allow.interval=5000

spring.r2dbc.url=r2dbc:mysql://host.docker.internal:3306/queueing_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.r2dbc.username=root
spring.r2dbc.password=tiffndla0423

redis.host = host.docker.internal
redis.port = 6379

spring.kafka.producer.bootstrap-servers=test-kafka:9092
queue.event.topic.name=test_queueing_system

spring.kafka.consumer.bootstrap-servers=test-kafka:9092
spring.kafka.consumer.group-id=test_consumer_group01
spring.kafka.consumer.auto-offset-reset=earliest

# --- Actuator ---
management.endpoints.web.exposure.include=*
management.server.port=9292

# Tomcat
server.tomcat.mbeanregistry.enabled=true