spring.application.name=QueueTest

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/queueing_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=tiffndla0423

redis.host = localhost
redis.port = 6379

spring.kafka.producer.bootstrap-servers=localhost:29092
queue.event.topic.name=test_queueing_system

spring.kafka.consumer.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=test_consumer_group01
spring.kafka.consumer.auto-offset-reset=earliest

# --- Actuator ---
management.endpoints.web.exposure.include=*
management.server.port=9292

# Tomcat
server.tomcat.mbeanregistry.enabled=true